# Generated by Django 4.2 on 2023-04-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP')),
                ('server_name', models.TextField(default='server', max_length=255, verbose_name='name')),
                ('server_is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Server',
                'managed': True,
            },
        ),
    ]
